#!/bin/bash

# check if user betty exists
if id -u betty >/dev/null 2>&1; then
    # switch to betty
    su betty
else
    echo "User betty does not exist"
fi
chmod +x switch-to-betty.sh
./switch-to-betty.sh
hk
